export { default as CtaSection } from './CtaSection.vue'
export { default as DashboardSection } from './DashboardSection.vue'
export { default as Footer } from './Footer.vue'
export { default as Header } from './Header.vue'
export { default as HeroSection } from './HeroSection.vue'
export { default as HowWorksSection } from './HowWorksSection.vue'
export { default as WhySection } from './WhySection.vue'
